'use strict';

const fs = require('node:fs'); const path = require('node:path');
const { immutableCopy } = require('../contracts/immutable'); const { assertProductSlug, getProductPath } = require('../state/product-state'); const { validateTask } = require('./plan');
const STATES = new Set(['pending', 'running', 'completed', 'failed', 'blocked']);
function assertToolkitId(id) { return assertProductSlug(id); }
function resolveToolkitTask(task, registry) { const resolved = validateTask({ ...task, task_id: task.task_id || task.id }, registry); return { ...resolved, id: task.id || resolved.task_id, idempotency_key: task.idempotency_key || task.id || resolved.task_id, started_at: null, completed_at: null, error: resolved.status === 'blocked' ? resolved.reason : null, artifact: null, attempts: 0, external_executable: false }; }
function assertDependencies(tasks) { const ids = new Set(tasks.map((task) => task.id)); for (const task of tasks) { if (task.depends_on !== undefined && (!Array.isArray(task.depends_on) || task.depends_on.some((id) => typeof id !== 'string'))) throw new TypeError('depends_on must be an array of task ids'); if (task.depends_on?.some((id) => !ids.has(id))) throw new Error('dependency not found'); } }
function gateInitialDependencies(tasks) { const byId = new Map(tasks.map((task) => [task.id, task])); return tasks.map((task) => { if (task.status === 'blocked' || !task.depends_on?.length) return task; if (task.depends_on.some((id) => ['blocked', 'failed'].includes(byId.get(id).status))) return { ...task, status: 'blocked', reason: 'dependency_blocked', error: 'dependency_blocked' }; return task; }); }
function toolkitDir(root, id) { return path.join(path.resolve(root), 'projeto', assertToolkitId(id)); }
function writeToolkitFiles(dir, state) { fs.mkdirSync(dir, { recursive: true }); for (const file of ['roteiro.md', 'plano.md']) { const target = path.join(dir, file); if (!fs.existsSync(target)) fs.writeFileSync(target, '# Toolkit\n'); } fs.writeFileSync(path.join(dir, 'estado.md'), JSON.stringify(state)); }
function createToolkit(root, id, tasks, registry) { if (!id || !Array.isArray(tasks)) throw new TypeError('toolkit id and tasks required'); const resolved = tasks.map((task) => resolveToolkitTask(task, registry)); const keys = new Set(); for (const task of resolved) { if (!task.idempotency_key || keys.has(task.idempotency_key)) throw new Error('duplicate idempotency key'); keys.add(task.idempotency_key); } assertDependencies(resolved); const gatedTasks = gateInitialDependencies(resolved); const state = { paused: false, status: gatedTasks.every((task) => task.status === 'completed') ? 'completed' : gatedTasks.some((task) => task.status === 'blocked') ? 'blocked' : 'pending', tasks: gatedTasks }; const dir = toolkitDir(root, id); writeToolkitFiles(dir, state); return immutableCopy({ dir, state }); }
function createProductToolkit({ projectRoot, product_slug: productSlug, id, tasks, registry }) { return createToolkit(getProductPath(assertProductSlug(productSlug), projectRoot), id, tasks, registry); }
function readToolkit(root, id) { const file = path.join(toolkitDir(root, id), 'estado.md'); return { file, state: JSON.parse(fs.readFileSync(file, 'utf8')) }; }
function updateGlobalStatus(state) { if (state.tasks.every((task) => task.status === 'completed')) state.status = 'completed'; else if (state.tasks.some((task) => task.status === 'failed' || task.status === 'blocked')) state.status = 'blocked'; else state.status = 'pending'; }
function transition(root, id, taskId, status, extra = {}) { if (!STATES.has(status)) throw new TypeError('invalid status'); const { file, state } = readToolkit(root, id); if (state.paused && status === 'running') throw new Error('toolkit is paused'); const task = state.tasks.find((item) => item.id === taskId); if (!task) throw new Error('unknown task'); if (task.status === 'completed') return immutableCopy(state); if (task.status === 'blocked') throw new Error('blocked task requires re-evaluation'); if (task.status === 'failed' && (status !== 'running' || extra.retry !== true)) throw new Error('failed task requires explicit retry'); if (status === 'running' && task.depends_on?.some((dependency) => { const item = state.tasks.find((candidate) => candidate.id === dependency); return !item || ['failed', 'blocked'].includes(item.status); })) throw new Error('blocked dependency'); const now = extra.now || new Date().toISOString(); Object.assign(task, extra, { status, attempts: status === 'running' ? task.attempts + 1 : task.attempts, started_at: status === 'running' ? now : task.started_at, completed_at: status === 'completed' ? now : task.completed_at }); updateGlobalStatus(state); fs.writeFileSync(file, JSON.stringify(state)); return immutableCopy(state); }
function reevaluateTask(root, id, taskId, update, registry) { const { file, state } = readToolkit(root, id); const index = state.tasks.findIndex((task) => task.id === taskId); if (index < 0) throw new Error('unknown task'); const current = state.tasks[index]; const resolved = resolveToolkitTask({ ...current, ...update, id: current.id, task_id: current.task_id }, registry); state.tasks[index] = { ...resolved, attempts: current.attempts, artifact: current.artifact, started_at: current.started_at, completed_at: current.completed_at }; updateGlobalStatus(state); fs.writeFileSync(file, JSON.stringify(state)); return immutableCopy(state); }
function pauseToolkit(root, id) { const { file, state } = readToolkit(root, id); state.paused = true; fs.writeFileSync(file, JSON.stringify(state)); return immutableCopy(state); }
function resumeToolkit(root, id) { const { file, state } = readToolkit(root, id); state.paused = false; fs.writeFileSync(file, JSON.stringify(state)); return immutableCopy(state); }
module.exports = { STATES, resolveToolkitTask, createToolkit, createProductToolkit, transition, reevaluateTask, pauseToolkit, resumeToolkit };
