#!/usr/bin/env node
'use strict';

const assert = require('node:assert/strict'); const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const http = require('node:http'); const https = require('node:https'); const net = require('node:net'); const child = require('node:child_process');
const local = require('../../core/local/workflows'); const research = require('../../core/external/research'); const image = require('../../core/external/image'); const video = require('../../core/external/video'); const dashboard = require('../../core/external/social-dashboard'); const meta = require('../../core/external/meta-ads'); const report = require('../../core/external/ads-report'); const publisher = require('../../core/external/organic-publisher'); const plan = require('../../core/orchestration/plan'); const toolkit = require('../../core/orchestration/toolkit'); const { workflowRegistry } = require('../../core/workflows/registry'); const { MockSecretProvider } = require('../../core/secrets/provider'); const { createApprovalPolicy } = require('../../core/approvals/policy');
const { executeHermesLocalWorkflow } = require('../../adapters/hermes/local-workflows'); const hermesExternal = require('../../adapters/hermes/external-workflows'); const hermesMeta = require('../../adapters/hermes/meta-workflows'); const hermesPublisher = require('../../adapters/hermes/publisher-workflow'); const { getHermesHighTicketStatus } = require('../../adapters/hermes/high-ticket-status');
const hermesOrchestration = require('../../adapters/hermes/orchestration-workflows');
const { createCodexLocal, resolveCodexPlan, createCodexToolkit, evaluateCodexPublication } = require('../../adapters/codex/workflows'); const codexExternal = require('../../adapters/codex/external-workflows'); const codexMeta = require('../../adapters/codex/meta-workflows'); const { getCodexHighTicketStatus } = require('../../adapters/codex/high-ticket-status'); const { resolveCodexWorkflow } = require('../../adapters/codex/resolver');

const fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'three-runtime-real-')); const counters = { network_calls: 0, child_process_calls: 0, writes_outside_fixture: 0 }; const coverage = new Set(); const collected = [];
const original = { fetch: global.fetch, http: [http.request, http.get, https.request, https.get, net.connect], child: Object.fromEntries(['exec', 'execSync', 'spawn', 'spawnSync', 'execFile', 'execFileSync', 'fork'].map((k) => [k, child[k]])), fs: Object.fromEntries(['writeFileSync', 'appendFileSync', 'renameSync', 'mkdirSync', 'rmSync'].map((k) => [k, fs[k]])) };
function blockedNetwork() { counters.network_calls += 1; throw new Error('network forbidden'); } function blockedChild() { counters.child_process_calls += 1; throw new Error('child process forbidden'); }
function guard(target) { if (typeof target !== 'number') { const resolved = path.resolve(String(target)); if (resolved !== fixture && !resolved.startsWith(`${fixture}${path.sep}`)) { counters.writes_outside_fixture += 1; throw new Error(`write outside fixture: ${resolved}`); } } }
function install() { if (typeof global.fetch === 'function') global.fetch = blockedNetwork; [http, https].forEach((mod) => { mod.request = blockedNetwork; mod.get = blockedNetwork; }); net.connect = blockedNetwork; for (const key of Object.keys(original.child)) child[key] = blockedChild; fs.writeFileSync = (p, ...a) => { guard(p); return original.fs.writeFileSync(p, ...a); }; fs.appendFileSync = (p, ...a) => { guard(p); return original.fs.appendFileSync(p, ...a); }; fs.renameSync = (a, b, ...rest) => { guard(a); guard(b); return original.fs.renameSync(a, b, ...rest); }; fs.mkdirSync = (p, ...a) => { guard(p); return original.fs.mkdirSync(p, ...a); }; fs.rmSync = (p, ...a) => { guard(p); return original.fs.rmSync(p, ...a); }; }
function restore() { global.fetch = original.fetch; [http.request, http.get, https.request, https.get, net.connect] = original.http; for (const [k, v] of Object.entries(original.child)) child[k] = v; for (const [k, v] of Object.entries(original.fs)) fs[k] = v; }
function copy() { return Array.from({ length: 16 }, (_, i) => `## Bloco ${String(i + 1).padStart(2, '0')}\nTexto específico validado.`).join('\n\n'); }
function manual(workflow_id, action_id) { return createApprovalPolicy({ mode: 'manual', workflow_id, manual_grant: { action_id, approved_by: 'fixture', approved_at: '2026-09-07T00:00:00.000Z' } }); }
function assertEquivalent(label, values, fields) { const normalized = values.map((item) => Object.fromEntries(fields.map((field) => [field, item[field]]))); assert.deepEqual(normalized[1], normalized[0], `${label}: Hermes`); assert.deepEqual(normalized[2], normalized[0], `${label}: Codex`); }

install();
try {
  const roots = ['claude', 'hermes', 'codex'].map((runtime) => path.join(fixture, runtime)); const slug = 'produto-paridade'; const productInput = { product_slug: slug, name: 'Produto Paridade', type: 'Low Ticket', price: 'R$47' };
  const claudeCreate = local.createProduct({ projectRoot: roots[0], slug, name: productInput.name, type: productInput.type, price: productInput.price });
  const hermesCreate = executeHermesLocalWorkflow({ workflow_id: 'product.create', projectRoot: roots[1], ...productInput }).result; const codexCreate = createCodexLocal({ workflow_id: 'product.create', projectRoot: roots[2], ...productInput }).result;
  assertEquivalent('product.create', [claudeCreate, hermesCreate, codexCreate], ['slug']); coverage.add('product.create');
  const cSelect = local.activateProduct({ projectRoot: roots[0], slug }); const hSelect = executeHermesLocalWorkflow({ workflow_id: 'product.select', projectRoot: roots[1], product_slug: slug }).result; const xSelect = createCodexLocal({ workflow_id: 'product.select', projectRoot: roots[2], product_slug: slug }).result; assertEquivalent('product.select', [cSelect, hSelect, xSelect], ['slug']); collected.push(cSelect, hSelect, xSelect); for (const root of roots) for (const file of ['pesquisa-mercado.md', 'perfil.md', 'idconsumidor.md']) fs.writeFileSync(path.join(root, 'meus-produtos', slug, file), '# fixture\n'); coverage.add('product.select');
  const content = copy(); const localWorkflows = ['copy.page', 'copy.ad', 'copy.social', 'copy.script'];
  for (const workflow_id of localWorkflows) { const base = { workflow_id, product_slug: slug, projectRoot: roots[0], content: workflow_id === 'copy.page' ? content : 'Texto específico validado.', page_type: 'vendas', offer: 'Oferta', platform: 'instagram', objective: 'vender' }; const cReview = local.reviewCopy({ workflow_id, content: base.content }); const c = local.saveReviewedCopy({ ...base, review: cReview }); const h = executeHermesLocalWorkflow({ ...base, projectRoot: roots[1] }).result; const x = createCodexLocal({ ...base, projectRoot: roots[2] }).result; assertEquivalent(workflow_id, [c, h, x], ['status']); collected.push(c, h, x); coverage.add(workflow_id); }
  for (const workflow_id of ['funnel.low_ticket', 'funnel.middle_ticket']) { const input = { workflow_id, product_slug: slug, quiz_required: true }; const c = workflow_id.endsWith('low_ticket') ? local.createLowTicketPlan({ projectRoot: roots[0], ...input }) : local.createMiddleTicketPlan({ projectRoot: roots[0], ...input }); const h = executeHermesLocalWorkflow({ ...input, projectRoot: roots[1] }).result; const x = createCodexLocal({ ...input, projectRoot: roots[2] }).result; assert.equal(c.plan.traffic_handoff.mode, h.plan.traffic_handoff.mode); assert.equal(c.plan.traffic_handoff.mode, x.plan.traffic_handoff.mode); collected.push(c, h, x); coverage.add(workflow_id); }
  const pageReview = local.reviewCopy({ workflow_id: 'copy.page', content }); const html = '<html><body><img src="assets/mock.png"></body></html>'; const cPage = local.buildPage({ projectRoot: roots[0], product_slug: slug, html, copy_review: pageReview }); const hPage = executeHermesLocalWorkflow({ workflow_id: 'page.sales', projectRoot: roots[1], product_slug: slug, html, copy_review: pageReview }).result; const xPage = createCodexLocal({ workflow_id: 'page.sales', projectRoot: roots[2], product_slug: slug, html, copy_review: pageReview }).result; assertEquivalent('page.sales', [cPage, hPage, xPage], ['status']); collected.push(cPage, hPage, xPage); coverage.add('page.sales');
  const carouselInput = { product_slug: slug, slug: 'post', slides: ['Um', 'Dois'], caption: 'Legenda', cta: 'CTA', visual_prompts: ['Prompt um', 'Prompt dois'] }; const cCarousel = local.createCarouselArtifact({ projectRoot: roots[0], ...carouselInput }); const hCarousel = executeHermesLocalWorkflow({ workflow_id: 'carousel.generate', projectRoot: roots[1], ...carouselInput }).result; const xCarousel = createCodexLocal({ workflow_id: 'carousel.generate', projectRoot: roots[2], ...carouselInput }).result; assert.equal(cCarousel.artifact.publication.autopublish, false); assert.equal(hCarousel.artifact.publication.autopublish, false); assert.equal(xCarousel.artifact.publication.autopublish, false); coverage.add('carousel.generate');
  const scheduleInput = { projectRoot: roots[0], product_slug: slug, slug: 'post', schedule_id: 'schedule', schedule: '0 9 * * 1', timezone: 'America/Manaus' }; const cSchedule = local.createCarouselSchedule(scheduleInput); const hSchedule = hermesOrchestration.createHermesCarouselSchedule({ ...scheduleInput, projectRoot: roots[1] }).result; const xSchedule = createCodexLocal({ workflow_id: 'carousel.schedule', ...scheduleInput, projectRoot: roots[2] }).result; assertEquivalent('carousel.schedule', [cSchedule, hSchedule, xSchedule], ['status']); collected.push(cSchedule, hSchedule, xSchedule); coverage.add('carousel.schedule');
  const cCommercial = local.planCommercial({ product_slug: slug, module: 'COMMERCIAL_HT', existing_artifacts: ['existente.md'] }); const hCommercial = executeHermesLocalWorkflow({ workflow_id: 'commercial.playbook', projectRoot: roots[1], product_slug: slug, module: 'COMMERCIAL_HT', existing_artifacts: ['existente.md'] }).result; const xCommercial = createCodexLocal({ workflow_id: 'commercial.playbook', projectRoot: roots[2], product_slug: slug, module: 'COMMERCIAL_HT', existing_artifacts: ['existente.md'] }).result; assert.equal(cCommercial.status, 'BLOCKED_EXTERNAL'); assert.equal(hCommercial.status, cCommercial.status); assert.equal(xCommercial.status, cCommercial.status); collected.push(cCommercial, hCommercial, xCommercial); coverage.add('commercial.playbook');
  const secrets = new MockSecretProvider({ APIFY_API_TOKEN: 'op://fixture/apify/token', OPENROUTER_API_KEY: 'op://fixture/openrouter/key', FREEPIK_API_KEY: 'op://fixture/freepik/key', META_ACCESS_TOKEN: 'op://fixture/meta/token' });
  const externalCases = [{ id: 'research.market', input: { provider: 'apify' } }, { id: 'image.generate', input: { provider: 'openrouter', prompt: 'Prompt' } }, { id: 'creative.static', input: { brief: 'Brief' } }, { id: 'video.generate', input: { renderer: 'ffmpeg', script: 'Roteiro' } }, { id: 'social.dashboard', input: { platform: 'instagram' } }];
  for (const item of externalCases) { const c = item.id === 'research.market' ? research.prepareSpecializedResearchProvider({ ...item.input, secretProvider: secrets }) : item.id === 'image.generate' ? image.prepareImageRequest({ ...item.input, secretProvider: secrets }) : item.id === 'video.generate' ? video.prepareVideoJob({ ...item.input, secretProvider: secrets }) : item.id === 'social.dashboard' ? dashboard.prepareDashboard({ ...item.input, secretProvider: secrets }) : { status: 'dry_run' }; const h = hermesExternal.prepareHermesExternalWorkflow({ workflow_id: item.id, ...item.input, secretProvider: secrets }).result; const x = codexExternal.prepareCodexExternalWorkflow({ workflow_id: item.id, ...item.input, secretProvider: secrets }).result; assert.equal(c.status, h.status); assert.equal(c.status, x.status); collected.push(c, h, x); coverage.add(item.id); }
  const reads = ['meta.auth.validate', 'meta.accounts.list', 'ads.account.read', 'ads.campaigns.list', 'ads.pixels.list', 'ads.conversions.list', 'ads.audiences.list', 'ads.interests.search', 'ads.creatives.validate', 'ads.insights']; for (const operation of reads) { const cRead = meta.prepareMetaOperation({ operation, auth_mode: 'MCP_CONECTOR' }); const hRead = hermesMeta.prepareHermesMetaOperation({ operation, auth_mode: 'MCP_CONECTOR' }).result; const xRead = codexMeta.prepareCodexMetaOperation({ operation, auth_mode: 'MCP_CONECTOR' }).result; assert.equal(cRead.status, 'dry_run'); assert.equal(hRead.status, 'dry_run'); assert.equal(xRead.status, 'dry_run'); collected.push(cRead, hRead, xRead); } coverage.add('ads.insights');
  for (const workflow_id of ['ads.campaign.create', 'ads.optimize', 'ads.scale']) { const action_id = `${workflow_id}-action`; const context = { workflow_id, action_id }; const policy = manual(workflow_id, action_id); const c = meta.prepareMetaOperation({ operation: workflow_id, context, policy, secretProvider: secrets }); const h = hermesMeta.prepareHermesMetaWorkflow({ workflow_id, context, policy, secretProvider: secrets }).result; const x = codexMeta.prepareCodexMetaWorkflow({ workflow_id, context, policy, secretProvider: secrets }).result; assert.equal(c.status, 'dry_run'); assert.equal(h.status, c.status); assert.equal(x.status, c.status); collected.push(c, h, x); coverage.add(workflow_id); }
  assert.equal(hermesMeta.createHermesCampaignDraft({ name: 'x', action_id: 'create' }).draft.status, 'PAUSED'); assert.equal(codexMeta.createCodexCampaignDraft({ name: 'x', action_id: 'create' }).draft.status, 'PAUSED');
  const reportInput = { product_slug: slug, period: '2026-09', metrics: { spend: 0 }, analysis: 'Mock' }; const cReport = report.createAdsReport({ ...reportInput, projectRoot: roots[0] }); const hReport = hermesMeta.buildHermesAdsReport({ ...reportInput, projectRoot: roots[1] }).result; const xReport = codexMeta.buildCodexAdsReport({ ...reportInput, projectRoot: roots[2] }).result; for (const item of [cReport, hReport, xReport]) assert.equal(item.delivery, null); collected.push(cReport, hReport, xReport); coverage.add('ads.report');
  const pub = { publication_id: 'publish', workflow_id: 'social.publish', product: slug, platform: 'instagram', content_type: 'post', artifact_path: 'entregas/post.md', approval_policy: manual('social.publish', 'publish'), autopublish: true }; assert.equal(publisher.evaluatePublication(publisher.createPublicationRequest(pub)).status, 'blocked'); assert.equal(hermesPublisher.evaluateHermesPublication(pub).result.status, 'blocked'); assert.equal(evaluateCodexPublication(pub).result.status, 'blocked'); coverage.add('social.publish');
  const tasks = [{ task_id: 'copy', workflow_id: 'copy.social' }, { task_id: 'unknown', workflow_id: 'unknown.workflow' }, { task_id: 'scale', workflow_id: 'ads.scale' }]; const cPlan = plan.resolvePlan(tasks, workflowRegistry); const hPlan = hermesOrchestration.resolveHermesPlan({ product_slug: slug, tasks }).result; const xPlan = resolveCodexPlan(tasks).result; assert.equal(cPlan.tasks[1].status, 'blocked'); assert.equal(hPlan.tasks[1].status, 'blocked'); assert.equal(xPlan.tasks[1].status, 'blocked'); collected.push(cPlan, hPlan, xPlan); coverage.add('plan.execute');
  const toolkitTasks = [{ id: 'copy', workflow_id: 'copy.social' }]; const cToolkit = toolkit.createProductToolkit({ projectRoot: roots[0], product_slug: slug, id: 'toolkit', tasks: toolkitTasks, registry: workflowRegistry }); const hToolkit = hermesOrchestration.createHermesToolkit({ projectRoot: roots[1], product_slug: slug, toolkit_id: 'toolkit', tasks: toolkitTasks }).result; const xToolkit = createCodexToolkit({ projectRoot: roots[2], product_slug: slug, toolkit_id: 'toolkit', tasks: toolkitTasks }).result; for (const item of [cToolkit, hToolkit, xToolkit]) assert.equal(item.state.tasks[0].status, 'pending'); collected.push(cToolkit, hToolkit, xToolkit); coverage.add('toolkit.execute');
  const ht = require('../../core/external/high-ticket-status').getHighTicketStatus({ projectRoot: roots[0], product_slug: slug }); assert.equal(ht.status, 'BLOCKED_EXTERNAL'); assert.equal(getHermesHighTicketStatus({ projectRoot: roots[1], product_slug: slug }).result.status, 'BLOCKED_EXTERNAL'); assert.equal(getCodexHighTicketStatus({ projectRoot: roots[2], product_slug: slug }).result.status, 'BLOCKED_EXTERNAL');
  const alias = resolveCodexWorkflow('traffic.insights'); assert.deepEqual({ requested: alias.requested_workflow_id, workflow: alias.workflow_id, alias: alias.compatibility_alias_of }, { requested: 'traffic.insights', workflow: 'ads.insights', alias: 'ads.insights' }); coverage.add('traffic.insights');
  collected.push(claudeCreate, hermesCreate, codexCreate, cCarousel, hCarousel, xCarousel, pub, ht, alias); assert.equal(coverage.size, 26); for (const workflow of workflowRegistry.list()) assert.equal(coverage.has(workflow.id), true, `not exercised: ${workflow.id}`); assert.deepEqual(counters, { network_calls: 0, child_process_calls: 0, writes_outside_fixture: 0 }); assert.equal(/op:\/\/|Bearer|Authorization|access_token=|password=|api_key=|EAA[A-Za-z0-9]+|sk-[A-Za-z0-9]+/.test(JSON.stringify(collected)), false);
} finally { restore(); fs.rmSync(fixture, { recursive: true, force: true }); }
assert.equal(fs.existsSync(fixture), false); process.stdout.write('Claude/Hermes/Codex real E2E parity: ok\n');
