#!/usr/bin/env node
'use strict';
const assert = require('node:assert/strict'); const { MockSecretProvider } = require('../../core/secrets/provider'); const { createApprovalPolicy } = require('../../core/approvals/policy'); const { META_ACCESS_TOKEN, META_SECRET_ALIASES, createMetaOperationDescriptor, prepareMetaOperation, createPausedCampaignDraft } = require('../../adapters/claude/meta-ads');
const secrets = new MockSecretProvider({ META_ACCESS_TOKEN: 'op://fixture/meta/token' });
const createPolicy = createApprovalPolicy({ mode: 'manual', workflow_id: 'ads.campaign.create', manual_grant: { action_id: 'create-1', approved_by: 'operator', approved_at: '2026-09-06T00:00:00Z' } });
assert.equal(prepareMetaOperation({ operation: 'ads.campaign.create', policy: createPolicy, context: { workflow_id: 'ads.campaign.create', action_id: 'create-1' }, secretProvider: secrets }).status, 'dry_run');
assert.equal(prepareMetaOperation({ operation: 'ads.insights', auth_mode: 'APP' }).reason, 'secret_unavailable');
const mcpRead = prepareMetaOperation({ operation: 'ads.insights', auth_mode: 'MCP_CONECTOR' }); assert.equal(mcpRead.status, 'dry_run'); assert.equal(mcpRead.transport, 'mcp'); assert.equal(mcpRead.oauth_managed_externally, true); assert.equal(mcpRead.secret_name, null);
const mcpCreateBlocked = prepareMetaOperation({ operation: 'ads.campaign.create', auth_mode: 'MCP_CONECTOR', policy: createApprovalPolicy({ mode: 'manual', workflow_id: 'ads.campaign.create' }), context: { workflow_id: 'ads.campaign.create', action_id: 'create-2' } }); assert.equal(mcpCreateBlocked.status, 'blocked');
const scaleContext = { workflow_id: 'ads.scale', action_id: 'scale-1' }; const noGrant = createApprovalPolicy({ mode: 'manual', workflow_id: 'ads.scale' }); assert.equal(prepareMetaOperation({ operation: 'ads.scale', policy: noGrant, context: scaleContext, secretProvider: secrets }).status, 'blocked'); assert.equal(prepareMetaOperation({ operation: 'ads.scale', auth_mode: 'MCP_CONECTOR', policy: noGrant, context: scaleContext }).status, 'blocked');
const correctGrant = createApprovalPolicy({ mode: 'manual', workflow_id: 'ads.scale', manual_grant: { action_id: 'scale-1', approved_by: 'operator', approved_at: '2026-09-06T00:00:00Z' } }); assert.equal(prepareMetaOperation({ operation: 'ads.scale', policy: correctGrant, context: scaleContext, secretProvider: secrets }).status, 'dry_run');
const draft = createPausedCampaignDraft({ name: 'Teste', action_id: 'create-1' }); assert.equal(draft.status, 'PAUSED'); assert.notEqual(draft.status, 'ACTIVE'); assert.equal(createMetaOperationDescriptor('ads.scale').financial, true); assert.equal(META_SECRET_ALIASES.ACCESS_TOKEN, META_ACCESS_TOKEN); assert.equal(typeof secrets.get_secret, 'undefined');
process.stdout.write('Claude Meta Ads workflow: ok\n');
